  - name: running firewalld service
    service:
      name: firewalld
      state: started

  - name: opening services for web access
#    become: yes
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - http
      - https
    notify: restart firewalld

  - name: opening ports for web access  
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - "{{ port_http }}"
      - "{{ port_https }}"
    notify: restart firewalld
